os: Visual Studio 2013

before_build:
# Change working directoty and current location
- ps: cd Code
- ps: "[Environment]::CurrentDirectory = $PWD"
# Download & Unzip FastBuild
- ps: (new-object net.webclient).DownloadFile('http://fastbuild.org/downloads/v0.91/FASTBuild-Windows-x64-v0.91.zip', 'C:/FastBuild.zip')
- ps: Add-Type -assembly "system.io.compression.filesystem"
- ps: "[io.compression.zipfile]::ExtractToDirectory(C:/Tmp/FastBuild.zip, C:/FastBuild)"
# Add FastBuild to path
- ps: "$env:Path = $env:Path + ';C:/FastBuild'"
# Generate VS projects
- ps: fbuild solution
 
# Using FastBuild
build_script:
- ps: fbuild

# Using MSbuild
#build:
#  project: C:\projects\tmp\VisualStudio\FASTBuild.sln
#  verbosity: minimal
  
after_build:
#Launch analysis
- ps: .\SonarQubeAnalysis.ps1 -hostUrl 'https://sonarqube.com' -login  d5fcf62e7cba7c67b913e9edb4ecee2e9a697d52 -sources Code/ -projectName $env:APPVEYOR_PROJECT_NAME -projectKey $env:APPVEYOR_PROJECT_SLUG -projectVersion $env:APPVEYOR_BUILD_NUMBER -buildWrapperCommand "msbuild  '../tmp/VisualStudio/FASTBuild.sln'  /t:rebuild"
